definitions:
  api.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
  application_cluster.ApplicationClusterRequest:
    properties:
      cluster_id:
        type: integer
    required:
    - cluster_id
    type: object
  applications.CreateAppRequest:
    properties:
      context:
        type: string
      status:
        type: integer
    required:
    - context
    - status
    type: object
  cluster.CreateClusterRequest:
    properties:
      kubeconfig:
        type: string
      marks:
        type: string
      name:
        type: string
    required:
    - kubeconfig
    - name
    type: object
  cluster_user.ClusterUserCreateRequest:
    properties:
      cluster_id:
        type: integer
      cpu:
        type: integer
      memory:
        type: integer
      user_id:
        type: integer
    required:
    - cluster_id
    - cpu
    - memory
    - user_id
    type: object
  model.ClusterList:
    properties:
      cluster_mark:
        type: string
      cluster_name:
        type: string
      created_at:
        type: string
      id:
        type: integer
      info:
        type: string
      users_count:
        type: integer
    type: object
  model.UserInfo:
    properties:
      avatar:
        type: string
      email:
        type: integer
      id:
        type: integer
      username:
        type: string
    type: object
  model.UserList:
    properties:
      cluster_count:
        type: integer
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      status:
        type: integer
    type: object
  user.CreateUserRequest:
    properties:
      confirm_password:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
      status:
        type: integer
    required:
    - confirm_password
    - email
    - name
    - password
    - status
    type: object
  user.LoginCredentials:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  user.RegisterRequest:
    properties:
      confirm_password:
        type: string
      email:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /login:
    post:
      description: 邮箱登录
      parameters:
      - description: Login user info
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/user.LoginCredentials'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"message":"OK","data":{"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"}}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - 用户
  /register:
    post:
      description: 用户注册
      parameters:
      - description: Reg user info
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/user.RegisterRequest'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"message":"OK","data":{"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"}}'
          schema:
            type: string
      summary: 注册
      tags:
      - 用户
  /users:
    get:
      consumes:
      - application/json
      description: Get an user by user id
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 用户信息
          schema:
            $ref: '#/definitions/model.UserInfo'
            type: object
      summary: 通过用户id获取用户信息
      tags:
      - 用户
  /v1/application:
    get:
      consumes:
      - application/json
      description: 用户获取应用
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"message":"OK","data":[{"id":1,"context":"application
            info","status":"1"}]}'
          schema:
            $ref: '#/definitions/api.Response'
            type: object
      summary: 获取应用
      tags:
      - 应用
    post:
      consumes:
      - application/json
      description: 用户添加应用
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: The application info
        in: body
        name: CreateAppRequest
        required: true
        schema:
          $ref: '#/definitions/applications.CreateAppRequest'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"message":"OK","data":null}'
          schema:
            $ref: '#/definitions/api.Response'
            type: object
      summary: 添加应用
      tags:
      - 应用
  /v1/application/{id}:
    delete:
      consumes:
      - application/json
      description: 用户软删除应用
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 应用 ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"message":"OK","data":null}'
          schema:
            $ref: '#/definitions/api.Response'
            type: object
      summary: 删除应用
      tags:
      - 应用
    put:
      consumes:
      - application/json
      description: 用户编辑应用
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 应用 ID
        in: path
        name: id
        required: true
        type: integer
      - description: The application info
        in: body
        name: CreateAppRequest
        required: true
        schema:
          $ref: '#/definitions/applications.CreateAppRequest'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"message":"OK","data":null}'
          schema:
            $ref: '#/definitions/api.Response'
            type: object
      summary: 编辑应用
      tags:
      - 应用
  /v1/application/{id}/bind_cluster:
    post:
      consumes:
      - application/json
      description: 应用关联集群
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: The application info
        in: body
        name: CreateAppRequest
        required: true
        schema:
          $ref: '#/definitions/application_cluster.ApplicationClusterRequest'
          type: object
      - description: 应用 ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"message":"OK","data":null}'
          schema:
            $ref: '#/definitions/api.Response'
            type: object
      summary: 关联集群
      tags:
      - 应用
  /v1/application/{id}/create_space:
    post:
      consumes:
      - application/json
      description: 为用户创建开发环境 - 集群授权
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: cluster user info
        in: body
        name: CreateAppRequest
        required: true
        schema:
          $ref: '#/definitions/cluster_user.ClusterUserCreateRequest'
          type: object
      - description: 应用 ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"message":"OK","data":null}'
          schema:
            $ref: '#/definitions/api.Response'
            type: object
      summary: 应用管理 - 创建开发环境
      tags:
      - 应用
  /v1/cluster:
    post:
      consumes:
      - application/json
      description: 用户添加集群，暂时不考虑验证集群的 kubeconfig
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: The cluster info
        in: body
        name: createCluster
        required: true
        schema:
          $ref: '#/definitions/cluster.CreateClusterRequest'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"message":"OK","data":null}'
          schema:
            $ref: '#/definitions/api.Response'
            type: object
      summary: 添加集群
      tags:
      - 集群
  /v1/cluster/list:
    get:
      consumes:
      - application/json
      description: 获取集群列表
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"message":"OK","data":model.ClusterList}'
          schema:
            $ref: '#/definitions/model.ClusterList'
            type: object
      summary: 获取集群列表
      tags:
      - 集群
  /v1/users:
    post:
      description: 管理员添加开发者
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Reg user info
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/user.CreateUserRequest'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"message":"OK","data":null}'
          schema:
            type: string
      summary: 添加开发者
      tags:
      - 用户
  /v1/users/{id}:
    delete:
      consumes:
      - application/json
      description: 管理员删除用户
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户 ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"message":"OK","data":null}'
          schema:
            $ref: '#/definitions/api.Response'
            type: object
      summary: 删除用户
      tags:
      - 用户
    put:
      consumes:
      - application/json
      description: Update a user by ID
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: The user's database id index num
        in: path
        name: id
        required: true
        type: integer
      - description: Update user info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.CreateUserRequest'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"message":"OK","data":null}'
          schema:
            $ref: '#/definitions/api.Response'
            type: object
      summary: 更新用户信息（含禁用用户）
      tags:
      - 用户
  /v1/users/list:
    get:
      consumes:
      - application/json
      description: Get userlist
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 用户列表
          schema:
            $ref: '#/definitions/model.UserList'
            type: object
      summary: 获取用户列表
      tags:
      - 用户
