// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: user.proto

package v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PhoneLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         int64                  `protobuf:"varint,1,opt,name=Phone,proto3" json:"Phone,omitempty"`
	VerifyCode    int32                  `protobuf:"varint,2,opt,name=VerifyCode,proto3" json:"VerifyCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneLoginRequest) Reset() {
	*x = PhoneLoginRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneLoginRequest) ProtoMessage() {}

func (x *PhoneLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneLoginRequest.ProtoReflect.Descriptor instead.
func (*PhoneLoginRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *PhoneLoginRequest) GetPhone() int64 {
	if x != nil {
		return x.Phone
	}
	return 0
}

func (x *PhoneLoginRequest) GetVerifyCode() int32 {
	if x != nil {
		return x.VerifyCode
	}
	return 0
}

type PhoneLoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           string                 `protobuf:"bytes,1,opt,name=Ret,proto3" json:"Ret,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneLoginReply) Reset() {
	*x = PhoneLoginReply{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneLoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneLoginReply) ProtoMessage() {}

func (x *PhoneLoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneLoginReply.ProtoReflect.Descriptor instead.
func (*PhoneLoginReply) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *PhoneLoginReply) GetRet() string {
	if x != nil {
		return x.Ret
	}
	return ""
}

func (x *PhoneLoginReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\auser.v0\"I\n" +
	"\x11PhoneLoginRequest\x12\x14\n" +
	"\x05Phone\x18\x01 \x01(\x03R\x05Phone\x12\x1e\n" +
	"\n" +
	"VerifyCode\x18\x02 \x01(\x05R\n" +
	"VerifyCode\"5\n" +
	"\x0fPhoneLoginReply\x12\x10\n" +
	"\x03Ret\x18\x01 \x01(\tR\x03Ret\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err2U\n" +
	"\vUserService\x12F\n" +
	"\fLoginByPhone\x12\x1a.user.v0.PhoneLoginRequest\x1a\x18.user.v0.PhoneLoginReply\"\x00B\x06Z\x04.;v0b\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_proto_goTypes = []any{
	(*PhoneLoginRequest)(nil), // 0: user.v0.PhoneLoginRequest
	(*PhoneLoginReply)(nil),   // 1: user.v0.PhoneLoginReply
}
var file_user_proto_depIdxs = []int32{
	0, // 0: user.v0.UserService.LoginByPhone:input_type -> user.v0.PhoneLoginRequest
	1, // 1: user.v0.UserService.LoginByPhone:output_type -> user.v0.PhoneLoginReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
