app:
  run_mode: debug                 # gin 开发模式, debug, release, test
  addr: :8080                     # HTTP绑定端口
  name: nocalhost                 # API Server Name
  url: http://127.0.0.1:8080      # pingServer
  max_ping_count: 10              # pingServer
  jwt_secret: IjTccFjAFvqYeNe9vuTOxHH6hu6vd4eiDCXumkGxDufKjmu4VGVN4h0ibIZx9L6Lr3KimVFiH05TUE4HPeQhhm01RcCfutq5Vlx
log:
  writers: stdout                 # 有2个可选项：file,stdout, 可以两者同时选择输出位置，有2个可选项：file,stdout。
  logger_level: DEBUG             # 日志级别，DEBUG, INFO, WARN, ERROR, FATAL
  #logger_file: /data/log/nocalhost.log   # 日志文件
  #logger_warn_file: /data/log/nocalhost.wf.log
  #logger_error_file: /data/log/nocalhost.err.log
  #log_format_text: false          # 日志的输出格式，json 或者 plaintext，目前设置为 false 即可，暂时也只支持 json 格式
  #log_rolling_policy: daily,      # rotate 依据，可选的有：daily, hourly。如果选daily(默认)则根据天进行转存，如果是hourly则根据小时进行转存
  #log_rotate_date: 1              # rotate 转存时间，配合rollingPolicy: daily 使用
  #log_rotate_size: 1              # rotate 转存大小，配合rollingPolicy: size 使用
  #log_backup_count: 7             # 当日志文件达到转存标准时，log 系统会将该日志文件进行压缩备份，这里指定了备份文件的最大个数。
mysql:
  name: nocalhost
  addr: 127.0.0.1:3306
  username: root
  password:
  show_log: true                  # 打印 SQL 日志
  max_idle_conn: 10               # 最大闲置的连接数
  max_open_conn: 60               # 最大打开的连接数, 需要小于数据库配置中的 max_connections 数
  conn_max_life_time: 60          # 连接重用的最大时间，单位分钟
cache:
  driver: "redis"                 # 缓存驱动，可以选memory、redis, 默认redis
  prefix: "nocalhost:"            # cache key前缀
redis:
  addr: "localhost:6379"
  password: "" # no password set
  db: 0 # use default DB
  dial_timeout: 60s   # 单位：秒
  read_timeout: 2s   # 单位：秒
  write_timeout: 2s  # 单位：秒
  pool_size: 60
  pool_timeout: 30s
