/*
* Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.
* This source code is licensed under the Apache License Version 2.0.
*/

package local

// SJTYMUE-DI3REKX-JCLCRXU-F6UJHCG-XQGHAZJ-5O5D3JR-LALGSBC-TJ4I4QO
var Cert = []byte(`-----BEGIN CERTIFICATE-----
MIIBsDCCATagAwIBAgIIBDvOdnVQJg4wCgYIKoZIzj0EAwIwFDESMBAGA1UEAxMJ
c3luY3RoaW5nMB4XDTIwMTIwMjAwMDAwMFoXDTQwMTEyNzAwMDAwMFowFDESMBAG
A1UEAxMJc3luY3RoaW5nMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEyu0MbGCCnm/s
kkyndZaQzuR5KLoLkFmiUhQrhiOr2xldzfeiqAw1MCCcW+mQW4QmLXPXc/++3kw4
zNyTREt4W2oJyAJBiLc+i8D83hQTIyhIpNomkDIiC3OnoUPD6nf3o1UwUzAOBgNV
HQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1Ud
EwEB/wQCMAAwFAYDVR0RBA0wC4IJc3luY3RoaW5nMAoGCCqGSM49BAMCA2gAMGUC
MBEWyW2WfM8Z2JOpCZ1u2e7B4c/yXY728cZRp8eVw/aolEi1ToDxBeIbWyOH8GQc
vwIxAP8CBDPdtzOQ6T7k6I/NQzsgLPNJZsRdSaf5b98G69qXPrWBI0cv6zcLecmQ
+ZqHTw==
-----END CERTIFICATE-----`)

var Key = []byte(`
-----BEGIN EC PRIVATE KEY-----
MIGkAgEBBDBkOppQcNCP1Xzm8hv1iDsXutI4SZlxECBT2EejaPrXWYAzFvil8Qiu
4Qsizmn40xygBwYFK4EEACKhZANiAATK7QxsYIKeb+ySTKd1lpDO5HkouguQWaJS
FCuGI6vbGV3N96KoDDUwIJxb6ZBbhCYtc9dz/77eTDjM3JNES3hbagnIAkGItz6L
wPzeFBMjKEik2iaQMiILc6ehQ8Pqd/c=
-----END EC PRIVATE KEY-----`)
