---
# Source: dep/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nocalhost-admin-service-account
  namespace: nocalhost-reserved
---
# Source: dep/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nocalhost-reserved-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: nocalhost-admin-service-account
    namespace: nocalhost-reserved