name: nocalhost
type: helmGit
resourcePath: ["deployments/chart"]

onPreInstall: []

services:
  - name: nocalhost-api
    serviceType: deployment
    gitUrl: https://e.coding.net/codingcorp/nocalhost/nocalhost.git
    devContainerImage: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/golang:latest
    workDir: /home/nocalhost-dev
    syncDirs:
    - .
    devPorts:
    - :8080
    dependPodsLabelSelector:
    - "app.kubernetes.io/name=mariadb"
  - name: nocalhost-web
    serviceType: deployment
    gitUrl: https://e.coding.net/codingcorp/nocalhost/nocalhost-web.git
    devContainerImage: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/node:12.18.1-slim
    workDir: /home/nocalhost-dev
    syncDirs:
    - .
    devPort:
    - :80
    dependPodsLabelSelector:
    - "app=nocalhost-api"