name: api-docker

on:
  push:
    branches: [ main, dev ]
#    paths:
#    - 'cmd/nocalhost-api/**'
#    - 'internal/nocalhost-api/**'
#    - 'pkg/nocalhost-api/**'
#    - '!*/**.md'
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build-api:
    name: Build api server docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build api-docker
        run: make api-docker
        env:
          SERVICE_INITIAL: true

      - name: Push to Github packages
        if: ${{ github.ref == 'refs/heads/main'}}
        env:
          GITHUB_IMAGE_NAME: docker.pkg.github.com/${{ github.repository }}/nocalhost-api
        run: |
          echo ${{ secrets.GPR_PASS }} | docker login docker.pkg.github.com -u ${{ secrets.GPR_USER }} --password-stdin
          docker tag nocalhost-api:${GITHUB_SHA} ${GITHUB_IMAGE_NAME}:${GITHUB_SHA}
          docker push ${GITHUB_IMAGE_NAME}:${GITHUB_SHA}

      - name: Push main to Github packages
        if: ${{ github.ref == 'refs/heads/main'}}
        env:
          GITHUB_IMAGE_NAME: docker.pkg.github.com/${{ github.repository }}/nocalhost-api
        run: |
          echo ${{ secrets.GPR_PASS }} | docker login docker.pkg.github.com -u ${{ secrets.GPR_USER }} --password-stdin
          docker tag nocalhost-api:${GITHUB_SHA} ${GITHUB_IMAGE_NAME}:main
          docker push ${GITHUB_IMAGE_NAME}:main

      - name: Push dev to Github packages
        if: ${{ github.ref == 'refs/heads/dev'}}
        env:
          GITHUB_IMAGE_NAME: docker.pkg.github.com/${{ github.repository }}/nocalhost-api
        run: |
          echo ${{ secrets.GPR_PASS }} | docker login docker.pkg.github.com -u ${{ secrets.GPR_USER }} --password-stdin
          docker tag nocalhost-api:${GITHUB_SHA} ${GITHUB_IMAGE_NAME}:dev
          docker push ${GITHUB_IMAGE_NAME}:dev

      - name: Push to Coding Artifacts
        if: ${{ github.repository == 'nocalhost/nocalhost' }}
        env:
          CODING_IMAGE_NAME: nocalhost-docker.pkg.coding.net/nocalhost/public/nocalhost-api
        run: |
          echo ${{ secrets.CODING_ARTIFACTS_PASS }} | docker login nocalhost-docker.pkg.coding.net -u ${{ secrets.CODING_ARTIFACTS_USER }} --password-stdin
          docker tag nocalhost-api:${GITHUB_SHA} ${CODING_IMAGE_NAME}:${GITHUB_SHA}
          docker push ${CODING_IMAGE_NAME}:${GITHUB_SHA}

      - name: Push main to Coding Artifacts
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'nocalhost/nocalhost' }}
        env:
          CODING_IMAGE_NAME: nocalhost-docker.pkg.coding.net/nocalhost/public/nocalhost-api
        run: |
          echo ${{ secrets.CODING_ARTIFACTS_PASS }} | docker login nocalhost-docker.pkg.coding.net -u ${{ secrets.CODING_ARTIFACTS_USER }} --password-stdin
          docker tag nocalhost-api:${GITHUB_SHA} ${CODING_IMAGE_NAME}:main
          docker push ${CODING_IMAGE_NAME}:main

      - name: Push dev to Coding Artifacts
        if: ${{ github.ref == 'refs/heads/dev' && github.repository == 'nocalhost/nocalhost' }}
        env:
          CODING_IMAGE_NAME: nocalhost-docker.pkg.coding.net/nocalhost/public/nocalhost-api
        run: |
          echo ${{ secrets.CODING_ARTIFACTS_PASS }} | docker login nocalhost-docker.pkg.coding.net -u ${{ secrets.CODING_ARTIFACTS_USER }} --password-stdin
          docker tag nocalhost-api:${GITHUB_SHA} ${CODING_IMAGE_NAME}:dev
          docker push ${CODING_IMAGE_NAME}:dev

      - name: Push latest tag to Coding Artifacts
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'nocalhost/nocalhost' && startsWith(github.ref, 'refs/tags/v')}}
        env:
          CODING_IMAGE_NAME: nocalhost-docker.pkg.coding.net/nocalhost/public/nocalhost-api
        run: |
          echo ${{ secrets.CODING_ARTIFACTS_PASS }} | docker login nocalhost-docker.pkg.coding.net -u ${{ secrets.CODING_ARTIFACTS_USER }} --password-stdin
          docker tag nocalhost-api:${GITHUB_SHA} ${CODING_IMAGE_NAME}:${GITHUB_REF##*/}
          docker push ${CODING_IMAGE_NAME}:${GITHUB_REF##*/}
